name: Build and Deploy - Master
on:
  workflow_run:
    workflows: [Test]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm clean-install
      - run: npm run build

      - name: Upload dist
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localPath: dist
          remotePath: ${{ secrets.REMOTE_PATH }}
