name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm clean-install
      - run: npm run test:unit
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
